export const banners = [
  { name: "Star Wars", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342512/PRODS-MEDIA-BANNERS/starwars_earbff.webp" },
  { name: "Harry Potter", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342496/PRODS-MEDIA-BANNERS/harrypotter2_mmiwku.webp" },
  { name: "Stranger Things", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342529/PRODS-MEDIA-BANNERS/strangerthings_wnnbrb.webp" },
  { name: "Joker", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342498/PRODS-MEDIA-BANNERS/joker_abbpzp.webp" },
  { name: "Peaky Blinders", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342505/PRODS-MEDIA-BANNERS/peakyblinders_q1pvve.webp" },
  { name: "Breaking Bad", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342487/PRODS-MEDIA-BANNERS/breakingbad2_llrswg.webp" },
  { name: "Baby Yoda", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342483/PRODS-MEDIA-BANNERS/babyyoda_ws9i4z.webp" },
  { name: "Dune", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342491/PRODS-MEDIA-BANNERS/dune_kbiq6b.webp" },
  { name: "Grinch", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342493/PRODS-MEDIA-BANNERS/grinch_zvlbzy.webp" },
  { name: "Mike", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342502/PRODS-MEDIA-BANNERS/mike_lyaueq.webp" },
  { name: "The Simpsons", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342508/PRODS-MEDIA-BANNERS/simpsons_xj0faz.webp" },
  { name: "South  Park", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342511/PRODS-MEDIA-BANNERS/southpark_kux5yi.webp" },
  { name: "The Office", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342517/PRODS-MEDIA-BANNERS/theoffice_madagh.webp" },
  { name: "Friends", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342491/PRODS-MEDIA-BANNERS/friends_kt1seq.webp" },
  { name: "John Wick", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342536/PRODS-MEDIA-BANNERS/johnwick_mwv4hb.webp" },
  { name: "Venom", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342522/PRODS-MEDIA-BANNERS/venom_vljxhp.webp" },
  { name: "The Wolf of Wallstreet", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342524/PRODS-MEDIA-BANNERS/wolf-of-wallstreet_l87tfu.webp" },
  { name: "Spiderman", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342536/PRODS-MEDIA-BANNERS/spiderman_uxoe7e.webp" },
  { name: "Toy Story", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342519/PRODS-MEDIA-BANNERS/toystory2_pqiueg.webp" },
  { name: "Goku", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342537/PRODS-MEDIA-BANNERS/goku2_ithubo.webp" },
  { name: "McQueen", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342521/PRODS-MEDIA-BANNERS/mcqueen_sfppn5.webp" },
  { name: "Game Of Thrones", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342494/PRODS-MEDIA-BANNERS/gameofthrones_x8llll.webp" },
  { name: "Deadpool", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342537/PRODS-MEDIA-BANNERS/deadpool_rouc04.webp" },
  { name: "The Avengers", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342536/PRODS-MEDIA-BANNERS/avengers_oly3zo.webp" },
  { name: "Wall-E", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342524/PRODS-MEDIA-BANNERS/wall-e_vsuepc.webp" },
  { name: "Up", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342520/PRODS-MEDIA-BANNERS/up_na2n6x.webp" },
  { name: "The Walking Dead", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342519/PRODS-MEDIA-BANNERS/thewalkingdead_lbexbd.webp" },
  { name: "The Incredibles", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342518/PRODS-MEDIA-BANNERS/indredibles_tfcodt.webp" },
  { name: "Heath Ledger", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342514/PRODS-MEDIA-BANNERS/the-joker-heath-ledger_fzyu5k.webp" },
  { name: "The Mask", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342514/PRODS-MEDIA-BANNERS/themask_z4t5im.webp" },
  { name: "Darthttps://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342513/PRODS-MEDIA-BANNERS/starwars3_hzbxfn.webp" },
  { name: "Ratatouille", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342507/PRODS-MEDIA-BANNERS/ratatouille_npolhl.webp" },
  { name: "Sopranos", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342510/PRODS-MEDIA-BANNERS/sopranos_bpskoc.webp" },
  { name: "Rick And Morty", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342506/PRODS-MEDIA-BANNERS/rickandmorty_ikidak.webp" },
  { name: "Shrek", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342507/PRODS-MEDIA-BANNERS/shrek_ac942j.webp" },
  { name: "Finding Nemo", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342492/PRODS-MEDIA-BANNERS/findingnemo2_vfyotg.webp" },
  { name: "Minions", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342502/PRODS-MEDIA-BANNERS/minions_jfmdm3.webp" },
  { name: "Inside Out", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342495/PRODS-MEDIA-BANNERS/insideout2_brznqh.webp" },
  { name: "The Lion King", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342501/PRODS-MEDIA-BANNERS/lionking_yvbzbr.webp" },
  { name: "Jakehttps://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342495/PRODS-MEDIA-BANNERS/jake_p0b4mf.webp" },
  { name: "Voldemort", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342494/PRODS-MEDIA-BANNERS/harrypotter3_u6yjcb.webp" },
  { name: "Bumblebee", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342487/PRODS-MEDIA-BANNERS/bumblebee_kqbijf.webp" },
  { name: "Anger", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342486/PRODS-MEDIA-BANNERS/anger_l3pp7a.webp" },
  { name: "Buzz", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342485/PRODS-MEDIA-BANNERS/buzz_sl0ksd.webp" },
  { name: "Angry Birds", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342485/PRODS-MEDIA-BANNERS/angrybirds_xliccb.webp" },
  { name: "Demon Slayer", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342491/PRODS-MEDIA-BANNERS/demonslayer_vudmbt.webp" },
  { name: "Simba, Timon & Pumba", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342509/PRODS-MEDIA-BANNERS/simbaTimonAndPumbaa_eru5hz.webp" },
  { name: "Why So serious?", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342497/PRODS-MEDIA-BANNERS/joker-batman-the-dark-knight_u1gi0x.webp" },
  { name: "Lilo and Stitch", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342498/PRODS-MEDIA-BANNERS/liloandstitch_yig8g5.webp" },
];
