export const banners = [
  { name: "Star Wars", src: "" },
  { name: "Harry Potter", src: "" },
  { name: "Stranger Things", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342529/PRODS-MEDIA-BANNERS/strangerthings_wnnbrb.webp" },
  { name: "Joker", src: "" },
  { name: "Peaky Blinders", src: "" },
  { name: "Breaking Bad", src: "" },
  { name: "Babyhttps://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342483/PRODS-MEDIA-BANNERS/babyyoda_ws9i4z.webp" },
  { name: "Dune", src: "" },
  { name: "Grinch", src: "" },
  { name: "Mike", src: "" },
  { name: "The Simpsons", src: "" },
  { name: "South  Park", src: "" },
  { name: "The Office", src: "" },
  { name: "Friends", src: "" },
  { name: "John Wick", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342536/PRODS-MEDIA-BANNERS/johnwick_mwv4hb.webp" },
  { name: "Venom", src: "" },
  { name: "The Wolf of Wallstreet", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342524/PRODS-MEDIA-BANNERS/wolf-of-wallstreet_l87tfu.webp" },
  { name: "Spiderman", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342536/PRODS-MEDIA-BANNERS/spiderman_uxoe7e.webp" },
  { name: "Toy Story", src: "" },
  { name: "Sullivan", src: "" },
  { name: "Goku", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342537/PRODS-MEDIA-BANNERS/goku2_ithubo.webp" },
  { name: "McQueen", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342521/PRODS-MEDIA-BANNERS/mcqueen_sfppn5.webp" },
  { name: "Game Of Thrones", src: "" },
  { name: "Deadpool", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342537/PRODS-MEDIA-BANNERS/deadpool_rouc04.webp" },
  { name: "The Avengers", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342536/PRODS-MEDIA-BANNERS/avengers_oly3zo.webp" },
  { name: "Wall-E", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342524/PRODS-MEDIA-BANNERS/wall-e_vsuepc.webp" },
  { name: "Up", src: "" },
  { name: "The Walking Dead", src: "" },
  { name: "The Incredibles", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342518/PRODS-MEDIA-BANNERS/indredibles_tfcodt.webp" },
  { name: "Heath Ledger", src: "" },
  { name: "The Mask", src: "" },
  { name: "Darth Vader", src: "" },
  { name: "Ratatouille", src: "" },
  { name: "Sopranos", src: "" },
  { name: "Rick And Morty", src: "" },
  { name: "Shrek", src: "" },
  { name: "Finding Nemo", src: "" },
  { name: "Minions", src: "" },
  { name: "Inside Out", src: "" },
  { name: "The Lion King", src: "" },
  { name: "Jake", src: "" },
  { name: "Voldemort", src: "" },
  { name: "Bumblebee", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342487/PRODS-MEDIA-BANNERS/bumblebee_kqbijf.webp" },
  { name: "Anger", src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342486/PRODS-MEDIA-BANNERS/anger_l3pp7a.webp" },
  { name: "Buzz" , src: "https://res.cloudinary.com/andreyt/image/upload/q_auto/v1733342485/PRODS-MEDIA-BANNERS/buzz_sl0ksd.webp" },
  { name: "Angry Birds", src: "" },
  { name: "Demon Slayer", src: "" },
  { name: "Simba, Timon & Pumba", src: "" },
  { name: "Why So serious?", src: "" },
  { name: "Lilo and Stitch", src: "" }
];
